In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
D_SP = pd.read_excel ('~/Desktop/HW2.xlsx',sheet_name = 'SPX_DXY_MonthlyReturns', parse_date = True, header = 0, usecols = 'A:C', index_col =[0]) 

In [3]:
D_SP   # data for market factor and US dollar factor

S&P - 500 Index  US Dollar Index
2001-07-31        -0.984416        -1.916799
2001-08-31        -6.260163        -3.208739
2001-09-30        -8.075231        -0.008817
2001-10-31         1.906875         1.278547
2001-11-30         7.670629         1.105694
...                     ...              ...
2018-08-31         3.258530         0.619752
2018-09-30         0.569193        -0.008409
2018-10-31        -6.835016         2.097086
2018-11-30         2.037839         0.149289
2018-12-31        -9.029085        -1.129822

[210 rows x 2 columns]

In [4]:
mkt_return = D_SP.iloc[:,0].values.reshape(-1,1)
usd_return = D_SP.iloc[:,1].values.reshape(-1,1)

In [5]:
stock = pd.read_excel ('~/Desktop/HW2.xlsx',sheet_name = 'SP500Stocks', header = 1, usecols = 'B:HF')

In [6]:
stock

TICKER SECTOR  MarketCap  2001-07-31 00:00:00  2001-08-31 00:00:00  \
0      MMM   INDU     110949            -1.945100            -6.446533   
1      ABT   HLTH     127036            12.112976            -7.258951   
2     ABBV   HLTH     138674                  NaN                  NaN   
3     ABMD   HLTH      14640           -19.423240            -1.315789   
4      ACN   INFT      89887                  NaN            -0.401070   
..     ...    ...        ...                  ...                  ...   
500    XYL   INDU      11991                  NaN                  NaN   
501    YUM   DSCR      28707             4.214608            -6.842003   
502    ZBH   HLTH      21156                  NaN            -4.895105   
503   ZION   FINA       7830            -0.932129            -1.698511   
504    ZTS   HLTH      41098                  NaN                  NaN   

     2001-09-30 00:00:00  2001-10-31 00:00:00  2001-11-30 00:00:00  \
0              -5.475902             6.077282            10.339559   
1               4.326061             2.599966             3.812730   
2                    NaN                  NaN                  NaN   
3              -6.826667            24.441900           -12.741490   
4             -14.429530            37.803922            28.628344   
..                   ...                  ...                  ...   
500                  NaN                  NaN                  NaN   
501            -7.977550            28.990256            -6.206153   
502             2.022059            11.387387             4.367519   
503            -6.287271           -10.696854             1.164570   
504                  NaN                  NaN                  NaN   

     2001-12-31 00:00:00  2002-01-31 00:00:00  ...  2018-03-31 00:00:00  \
0               3.168009            -6.098369  ...            -6.789357   
1               1.363484             3.886888  ...            -0.679629   
2                    NaN                  NaN  ...           -18.285435   
3             -16.605166            -6.131479  ...             8.505481   
4              19.115044            -4.234770  ...            -4.664319   
..                   ...                  ...  ...                  ...   
500                  NaN                  NaN  ...             3.137550   
501             3.688246            13.414138  ...             4.607980   
502            -5.331680             6.516045  ...            -5.993991   
503             8.906415            -4.260132  ...            -4.074956   
504                  NaN                  NaN  ...             3.277277   

     2018-04-30 00:00:00  2018-05-31 00:00:00  2018-06-30 00:00:00  \
0             -11.447915             2.149656            -0.258595   
1              -2.525512             5.848923            -0.877646   
2               3.070457             2.475368            -6.357350   
3               3.422798            26.645622             7.322769   
4              -0.615572             3.002638             5.040437   
..                   ...                  ...                  ...   
500            -5.226213            -3.145842            -4.289844   
501             2.314109            -6.221202            -3.823932   
502             5.621732            -3.177918             0.152802   
503             3.830840             0.525614            -3.867899   
504             0.111571             0.263494             1.780188   

     2018-07-31 00:00:00  2018-08-31 00:00:00  2018-09-30 00:00:00  \
0               7.930319             0.006810            -0.099670   
1               7.939856             1.983455             9.754681   
2               0.546199             4.065904            -1.458604   
3             -13.328444            14.681409            10.617837   
4              -2.604036             6.113071             0.668382   
..                   ...                  ...                  ...   
500            13.624241            -0.578

In [7]:
ticker = stock.TICKER
mc = stock.MarketCap
mc1 = mc.map(lambda x: math.log(x)) 
logmc = np.array(mc1.values.tolist())

In [8]:
# check the number of sectors

In [9]:
x = stock.SECTOR.unique()

In [10]:
name_sec = x.copy()
name_sec = name_sec.tolist()
del name_sec[5]
name = name_sec
name

['INDU',
 'HLTH',
 'INFT',
 'TCOM',
 'DSCR',
 'FINA',
 'MATS',
 'REAL',
 'STPL',
 'ENER']

In [11]:
sector = stock.SECTOR.values

In [12]:
# thus we need 10 columns to specify every sector, 10zeros means 
# the category of UTIL
# However, in the convenience of calculate z-score of marketcap
# I will not delete it at first

In [13]:
sec_array = np.zeros([505,11])
sec_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
for i in range(0,505):
    for j in range(0,11):
        if sector[i] == x[j]:
            sec_array[i,j] = 1
        else:
            sec_array[i,j] = 0

In [15]:
sec_array

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [16]:
sec_frame = pd.DataFrame(sec_array, index = ticker, 
             columns=x)

In [17]:
sec_factor = sec_frame.drop(labels=None,axis=1, index=None, columns='UTIL', inplace=False)
sec_factor

INDU  HLTH  INFT  TCOM  DSCR  FINA  MATS  REAL  STPL  ENER
TICKER                                                            
MMM      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ABT      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ABBV     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ABMD     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ACN      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
XYL      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
YUM      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0
ZBH      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
ZION     0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0
ZTS      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[505 rows x 10 columns]

In [18]:
lgmc_frame = pd.DataFrame(logmc, index = ticker)
lgmc_frame.columns = ['lgmc']
mc_sec = pd.merge(sec_frame, lgmc_frame, left_index=True, right_index=True, how='left')
mc_sec

INDU  HLTH  INFT  TCOM  DSCR  UTIL  FINA  MATS  REAL  STPL  ENER  \
TICKER                                                                     
MMM      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABT      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABBV     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABMD     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ACN      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
XYL      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
YUM      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
ZBH      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ZION     0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   
ZTS      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

             lgmc  
TICKER             
MMM     11.616826  
ABT     11.752226  
ABBV    11.839881  
ABMD     9.591513  
ACN     11.406309  
...           ...  
XYL      9.391912  
YUM     10.264896  
ZBH      9.959679  
ZION     8.965718  
ZTS     10.623715  

[505 rows x 12 columns]

In [19]:
#test the demand...
test = mc_sec.iloc[:,-1][mc_sec['INDU'] == 1]
test.mean()

9.887828138254545

In [20]:
#def statistics_cap(sectorname):
mean_cap = []
vol_cap = []
for i in x:
    feature_data = mc_sec.iloc[:,-1][mc_sec[i] == 1]
    mean = feature_data.mean()
    vol = feature_data.std()
    mean_cap.append(mean)
    vol_cap.append(vol)  

In [21]:
z_score = np.zeros([505,1])
for i in range(0,505):
    for j in range(0,11):
        if mc_sec.iloc[i,j] == 1:
            z_score[i] = (mc_sec.lgmc[i] - mean_cap[j])/vol_cap[j]

In [22]:
z_frame = pd.DataFrame(z_score, index = ticker)
z_frame.columns = ['z_score']
z_sec = pd.merge(mc_sec, z_frame, left_index=True, right_index=True, how='left')

In [23]:
z_sec = z_sec.drop('UTIL', axis=1)

In [24]:
z_sec

INDU  HLTH  INFT  TCOM  DSCR  FINA  MATS  REAL  STPL  ENER       lgmc  \
TICKER                                                                          
MMM      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  11.616826   
ABT      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  11.752226   
ABBV     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  11.839881   
ABMD     0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   9.591513   
ACN      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  11.406309   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...        ...   
XYL      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   9.391912   
YUM      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  10.264896   
ZBH      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   9.959679   
ZION     0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   8.965718   
ZTS      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  10.623715   

         z_score  
TICKER            
MMM     1.977538  
ABT     1.350510  
ABBV    1.436935  
ABMD   -0.779869  
ACN     1.038986  
...          ...  
XYL    -0.567203  
YUM     0.586831  
ZBH    -0.416871  
ZION   -1.093636  
ZTS     0.237842  

[505 rows x 12 columns]

In [25]:
mreturn = stock.iloc[:,3:]

In [26]:
stock_mr = mreturn.iloc[:,:].transpose().values
stock_return = pd.DataFrame(stock_mr)
stock_return

0          1          2          3          4          5    \
0    -1.945100  12.112976        NaN -19.423240        NaN -13.577718   
1    -6.446533  -7.258951        NaN  -1.315789  -0.401070   9.226306   
2    -5.475902   4.326061        NaN  -6.826667 -14.429530 -26.532794   
3     6.077282   2.599966        NaN  24.441900  37.803922  32.808711   
4    10.339559   3.812730        NaN -12.741490  28.628344   3.113693   
..         ...        ...        ...        ...        ...        ...   
205   0.006810   1.983455   4.065904  14.681409   6.113071  -1.797917   
206  -0.099670   9.754681  -1.458604  10.617837   0.668382  15.381530   
207  -9.705245  -5.645529 -16.817462 -24.135631  -6.540393 -16.997247   
208  10.030197   7.412211  21.091854  -2.497069   4.377624 -27.762551   
209  -8.358958  -2.322711  -2.206395  -2.296501 -14.290059  -6.635818   

           6          7          8          9    ...        495        496  \
0   -20.234087        NaN -36.816609 -11.033682  ...  -2.816904        NaN   
1   -10.349165        NaN -25.794085 -13.524804  ...   9.043619        NaN   
2   -28.616782        NaN -39.852399 -61.292271  ...  24.348706        NaN   
3    10.091781        NaN  20.736196   8.034321  ...  -0.427533        NaN   
4    21.515301        NaN  37.804878  19.277978  ...   1.674522        NaN   
..         ...        ...        ...        ...  ...        ...        ...   
205   7.695744  16.144448  37.315876   1.714948  ...  -7.621376 -10.573686   
206   2.443937   2.657670  22.725467   4.011875  ...  -3.890365 -14.345417   
207  -8.960915  -5.091117 -41.048883   5.071835  ...   1.575161 -20.824818   
208   2.087400  11.235446  16.968699   6.241066  ...  11.378861   9.555415   
209  -9.825016 -11.360224 -13.333333  -6.649549  ...  -4.381490  -9.588670   

          497        498        499        500        501        502  \
0   -4.077114 -16.614480  -3.006790        NaN   4.214608        NaN   
1    1.707327  15.288163  -2.400000        NaN  -6.842003  -4.895105   
2    4.106134 -15.760939 -39.728484        NaN  -7.977550   2.022059   
3    0.461629  -9.677419  29.281768        NaN  28.990256  11.387387   
4   -3.429815  20.000215  18.704799        NaN  -6.206153   4.367519   
..        ...        ...        ...        ...        ...        ...   
205  2.539527   7.277686   8.521669  -0.578087  10.055781  -1.505699   
206 -0.977626  -2.256999   3.006522   5.216744   4.626532   6.538274   
207  3.812789   3.298736   6.486203 -17.628674  -0.549981 -13.600042   
208  7.018958  -3.408566   8.783834  11.283937   2.423112   3.019571   
209 -5.343231 -25.663481  -7.904418  -8.577682  -0.325260 -11.156387   

           503       504  
0    -0.932129       NaN  
1    -1.698511       NaN  
2    -6.287271       NaN  
3   -10.696854       NaN  
4     1.164570       NaN  
..         ...       ...  
205   3.662039  4.764175  
206  -5.892335  1.059554  
207  -6.181357 -1.539947  
208   4.055791  4.272029  
209 -16.276212 -8.873969  

[210 rows x 505 columns]

In [27]:
# stock_return = constant + mkt_return*beta1 + usd_return*beta2
#            +sec_factor*(beta3~beta12) + z_score*beta13

In [28]:
import statsmodels.api as sm

In [29]:
data1 = D_SP.to_numpy()
data2 = sm.add_constant(data1)

In [30]:
beta = np.zeros([505,2])
for i in range(0,505):
    Y = stock_return.iloc[:,i]
    m = sm.OLS(Y,data2,missing = 'drop').fit()
    beta[i,0] = m.params[1]
    beta[i,1] = m.params[2]
beta

array([[ 0.89727922,  0.13705929],
       [ 0.50103115, -0.09682999],
       [ 1.45009589, -0.55690148],
       ...,
       [ 0.72111827, -0.50389316],
       [ 1.13626781, -0.08487808],
       [ 0.97013304,  0.50179335]])

In [31]:
beta_frame = pd.DataFrame(beta, index = ticker, columns=['beta1','beta2'])

In [32]:
all_data = pd.merge(beta_frame, z_sec, left_index=True, right_index=True, how='left')

In [33]:
all_data = all_data.drop('lgmc',axis=1)
all_data

beta1     beta2  INDU  HLTH  INFT  TCOM  DSCR  FINA  MATS  REAL  \
TICKER                                                                       
MMM     0.897279  0.137059   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABT     0.501031 -0.096830   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABBV    1.450096 -0.556901   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
ABMD    1.263956  0.059849   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
ACN     1.152855  0.193686   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   
...          ...       ...   ...   ...   ...   ...   ...   ...   ...   ...   
XYL     1.037699 -0.747278   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
YUM     0.657877 -0.258958   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   
ZBH     0.721118 -0.503893   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   
ZION    1.136268 -0.084878   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   
ZTS     0.970133  0.501793   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   

        STPL  ENER   z_score  
TICKER                        
MMM      0.0   0.0  1.977538  
ABT      0.0   0.0  1.350510  
ABBV     0.0   0.0  1.436935  
ABMD     0.0   0.0 -0.779869  
ACN      0.0   0.0  1.038986  
...      ...   ...       ...  
XYL      0.0   0.0 -0.567203  
YUM      0.0   0.0  0.586831  
ZBH      0.0   0.0 -0.416871  
ZION     0.0   0.0 -1.093636  
ZTS      0.0   0.0  0.237842  

[505 rows x 13 columns]

In [34]:
Y1 = stock_mr
data3 = all_data.values
X1 = sm.add_constant(data3)

In [35]:
X1.shape

(505, 14)

In [36]:
factor_return = np.zeros([210,14])
for i in range(0,210):
    for j in range(0,14):
        Y11 = Y1[i]
        X11 = X1
        n = sm.OLS(Y11,X1,missing = 'drop').fit()
        factor_return[i,j] = n.params[j]

In [ ]:
#  calculate historical factor monthly returns for the following factors based on Arbitrage Pricing Theory

In [37]:
factor_return   # the factor_return matrix 

array([[  0.63347893,  -6.86285728,   1.14889942, ...,   6.4748542 ,
          5.31545158,  -0.94741375],
       [  4.24767744,  -6.53110722,  -3.81494125, ...,   0.5861965 ,
         -3.38138787,  -0.93846446],
       [  2.40236004, -20.77960007,  -4.42704275, ...,   6.04239303,
          4.08740578,  -0.14960713],
       ...,
       [  5.75378061,  -7.03079982,   3.36258877, ...,  -0.9762139 ,
        -10.51525155,   0.48634149],
       [  3.1498338 ,   0.49019469,   1.69933723, ...,  -2.04001118,
         -7.98362516,   0.58367353],
       [ -2.34129296,  -3.17679038,   0.48735719, ...,  -6.06136948,
         -8.85612179,   1.49874591]])

In [38]:
factor_return.shape

(210, 14)

In [ ]:
# check for each factor their historical returns are significant or not (based on T-stat).

In [39]:
import scipy as scipy
from scipy import stats

In [40]:
a = factor_return[:,0]
t_test = scipy.stats.ttest_1samp(a, 0, axis=0)
t_test

Ttest_1sampResult(statistic=2.740538900468859, pvalue=0.006664726304594911)

In [41]:
t_stat = np.zeros([14,2])
for i in range(0,14):
    a = factor_return[:,i]
    t_test = scipy.stats.ttest_1samp(a, 0, axis=0)
    t_stat[i,0] = t_test[0]
    t_stat[i,1] = t_test[1]

In [42]:
t_stat

array([[ 2.7405389 ,  0.00666473],
       [ 0.61238486,  0.54094885],
       [ 0.03022911,  0.97591318],
       [ 0.69370497,  0.48863751],
       [ 1.43657911,  0.15233284],
       [ 1.06625056,  0.28754055],
       [ 0.31314537,  0.75448249],
       [ 0.90989262,  0.36392727],
       [-0.46128547,  0.64507351],
       [ 0.84389424,  0.39969337],
       [ 1.1615769 ,  0.24673222],
       [ 0.52976137,  0.5968397 ],
       [ 0.41966536,  0.675161  ],
       [ 0.82920847,  0.40793248]])

In [ ]:
# using the last month in the back-test, i.e., 12/31/2018, show that:

In [ ]:
# all factor portfolios are long-short neutral portfolio, i.e., the total weights sum to 0. 

In [43]:
all_beta = X1
all_beta.shape

(505, 14)

In [44]:
# = np.linalg.inv(all_beta)
trans = all_beta.T

In [45]:
xt = stock.iloc[:,-1]
xt

0      -8.358958
1      -2.322711
2      -2.206395
3      -2.296501
4     -14.290059
         ...    
500    -8.577682
501    -0.325260
502   -11.156387
503   -16.276212
504    -8.873969
Name: 2018-12-31 00:00:00, Length: 505, dtype: float64

In [46]:
element = np.dot(np.linalg.inv(np.dot(trans,all_beta)),trans)

In [47]:
weight = []
for i in range(0,14):
    sum_weight = sum(element[i])
    weight.append(sum_weight)

In [48]:
weight

[1.0000000000000089,
 1.1752751549742868e-16,
 4.119968255444917e-16,
 -4.853756285783106e-15,
 -4.373237882937531e-15,
 -5.583641188300348e-15,
 -2.4507305906862342e-15,
 -2.9032765774816838e-15,
 -3.603020659603828e-15,
 -1.893233833594188e-15,
 -1.4925127106435454e-15,
 -1.233794967234192e-15,
 -1.844011054963346e-15,
 2.5326962749261384e-16]

In [49]:
np.around(weight, decimals=4, out=None)

array([ 1.,  0.,  0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
        0.])

In [50]:
# except for free_risk asset, 
# all factor portfolios are long-short neutral portfolio

In [ ]:
# for any factor portfolio, it has unit exposure to its own factor, but zero exposure to all other factors in the model. 

In [51]:
array_beta = np.dot(element,all_beta)

In [52]:
array_beta.shape

(14, 14)

In [53]:
np.around(array_beta, decimals=4, out=None)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        -0.],
       [ 0.,  1., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
         0.],
       [ 0.,  0.,  1., -0., -0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,
        -0.],
       [-0., -0., -0.,  1., -0., -0., -0., -0., -0.,  0., -0., -0., -0.,
         0.],
       [-0., -0., -0., -0.,  1., -0., -0., -0., -0., -0., -0., -0., -0.,
         0.],
       [-0., -0., -0., -0., -0.,  1., -0., -0., -0., -0., -0., -0., -0.,
         0.],
       [-0., -0., -0.,  0., -0., -0.,  1., -0., -0.,  0.,  0.,  0.,  0.,
         0.],
       [-0., -0., -0.,  0., -0., -0.,  0.,  1., -0.,  0.,  0.,  0.,  0.,
         0.],
       [-0., -0., -0.,  0., -0., -0., -0., -0.,  1.,  0., -0., -0., -0.,
         0.],
       [-0., -0., -0.,  0., -0., -0., -0.,  0., -0.,  1., -0., -0.,  0.,
         0.],
       [-0., -0., -0.,  0., -0., -0., -0., -0., -0.,  0.,  1., -0.,  0.,
         0.],
       [-0., -0., -0.,  0., -0., -0.,  0., 

In [54]:
# the array shows that for any factor portfolio, 
#it has unit exposure to its own factor, but zero exposure to all other factors in the model. 

In [ ]:
# use black-litterman model to find the new portfolio expected return :

In [55]:
tau = 0.05

In [56]:
month_var = 10*10*(1/12)
month_var

8.333333333333332

In [57]:
mean_all = np.mean(factor_return, axis=0)
ret_sec = np.around(mean_all[3:13], decimals=3, out=None) 
ret_sec
#INDU HLTH INFT TCOM DSCR FINA MATS REAL STPL ENER

array([ 0.209,  0.411,  0.327,  0.097,  0.311, -0.16 ,  0.261,  0.363,
        0.132,  0.174])

In [58]:
Pi = ret_sec

In [59]:
sigma = np.cov(factor_return[:,3:13].T)
sigma

array([[19.02114378, 13.4234903 , 13.72532806, 13.48221255, 17.59947258,
        17.21228829, 16.62323413,  9.20190977, 12.18445164, 13.18732194],
       [13.4234903 , 17.15926942, 12.88310397, 12.57150873, 13.98530558,
        14.55142226, 12.39714826,  9.24429851, 11.04895721,  8.96523111],
       [13.72532806, 12.88310397, 19.76850914, 14.62916081, 14.07562608,
        12.70689713, 14.43177831,  6.26767459, 10.35169808, 13.09362227],
       [13.48221255, 12.57150873, 14.62916081, 20.26570407, 15.55063706,
        14.19811771, 14.4470043 ,  7.09055879, 12.20769875, 13.248884  ],
       [17.59947258, 13.98530558, 14.07562608, 15.55063706, 24.47573702,
        18.23645574, 16.3435205 , 12.62768624, 13.87049292, 10.20387358],
       [17.21228829, 14.55142226, 12.70689713, 14.19811771, 18.23645574,
        25.33435414, 15.92056146, 11.4615958 , 13.25909458, 10.83499992],
       [16.62323413, 12.39714826, 14.43177831, 14.4470043 , 16.3435205 ,
        15.92056146, 20.0406239 ,  8.08468741

In [60]:
#without active views, given Pi (from 1) and Sigma (from 2), 
#locate the optimal portfolio of the 10 sectors which has the 
#highest expected return and at the same time its annualized 
#volatility no greater than 10%. 

In [61]:
import scipy.optimize as so
from scipy.optimize import minimize

In [62]:
def statistics(weights):
    weights1 = np.array(weights)
    port_ret = np.dot(weights1.T,ret_sec)
    port_var = np.dot(weights1.T, np.dot(sigma, weights1))
    return np.array([port_ret,port_var])

In [63]:
def min_negareturn(weights):
    return -statistics(weights)[0]

In [64]:
cons1=({'type': 'ineq', 'fun': lambda x: -statistics(x)[1] + month_var})

In [65]:
opt1 = so.minimize(min_negareturn,10*[1./10,],method='SLSQP', constraints=cons1)
#bounds=bnds, 

In [ ]:
# run the optimization to find the market portfolio's return 

In [66]:
old = np.around(opt1.x, decimals=4, out=None)
old

array([-0.0775,  0.6425,  0.1167, -0.3168,  0.266 , -0.7314,  0.2678,
        0.2189, -0.0537,  0.0379])

In [67]:
#INDU HLTH INFT TCOM DSCR FINA MATS REAL STPL ENER

In [ ]:
# add three views into portfolio:

In [68]:
view1 = np.zeros(10)
view1[9]=1

In [69]:
# active view1 return is 0.2%

In [70]:
view2 = np.zeros(10)
view2[5]=1
view2[0]=-1
view2

array([-1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [71]:
# active view2 return is 0.05%

In [72]:
#portion1 = ret_sec[2]/(ret_sec[1]+ret_sec[2])
#portion2 = ret_sec[7]/(ret_sec[8]+ret_sec[7])

In [73]:
view3 = np.zeros(10)
view3[2] = 0.5
view3[1] = 0.5
view3[7] = -0.5
view3[8] = -0.5

In [74]:
view3

array([ 0. ,  0.5,  0.5,  0. ,  0. ,  0. ,  0. , -0.5, -0.5,  0. ])

In [75]:
# active view3 return is 0.3%

In [76]:
act_return = np.array([[0.2],[0.05],[0.3]])
act_return

array([[0.2 ],
       [0.05],
       [0.3 ]])

In [77]:
def omega(view):
    omega = tau*(np.dot(np.dot(view,sigma), view.T))
    return omega

In [78]:
omega_array = np.zeros([3,3])
view = [view1,view2,view3]

In [79]:
p = np.concatenate((view1,view2,view3),axis=0)
P = p.reshape(3,10)
P

array([[ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ],
       [-1. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  0.5,  0. ,  0. ,  0. ,  0. , -0.5, -0.5,  0. ]])

In [80]:
Q =  act_return
Q

array([[0.2 ],
       [0.05],
       [0.3 ]])

In [81]:
omega(view[0])

1.810441120693

In [82]:
for i in range(0,3):
    omega_array[i,i] = omega(view[i])

In [83]:
omega_array

array([[1.81044112, 0.        , 0.        ],
       [0.        , 0.49654607, 0.        ],
       [0.        , 0.        , 0.47926927]])

In [84]:
np.linalg.inv(omega_array)

array([[0.55235157, 0.        , 0.        ],
       [0.        , 2.01391183, 0.        ],
       [0.        , 0.        , 2.08650976]])

In [85]:
C = tau*sigma
x1 = np.dot(np.dot(P.T,np.linalg.inv(omega_array)),P)
x2 = np.linalg.inv(C)
H = x1+x2

In [86]:
y = np.dot(np.linalg.inv(C),Pi).reshape(-1,1)
z = np.dot(np.dot(P.T,np.linalg.inv(omega_array)), Q)
x = z+y

In [87]:
x = y+z

In [88]:
nu = np.dot(np.linalg.inv(H),x)
nu

array([[0.20306014],
       [0.49128393],
       [0.39553896],
       [0.15854739],
       [0.33514042],
       [0.03443175],
       [0.28970436],
       [0.34065788],
       [0.15930972],
       [0.19492637]])

In [89]:
Pi

array([ 0.209,  0.411,  0.327,  0.097,  0.311, -0.16 ,  0.261,  0.363,
        0.132,  0.174])

In [90]:
up_cov = np.linalg.inv(H)+sigma
up_cov

array([[19.83975771, 13.99893367, 14.25929364, 14.02651491, 18.38994766,
        17.9994606 , 17.30343841,  9.6791279 , 12.73014605, 13.49955693],
       [13.99893367, 17.90860421, 13.37013324, 13.08073992, 14.61801106,
        15.17056066, 12.89497642,  9.75855627, 11.55295329,  9.15992955],
       [14.25929364, 13.37013324, 20.51037898, 15.18848345, 14.68873406,
        13.23912861, 14.96902782,  6.68521562, 10.80803068, 13.36442591],
       [14.02651491, 13.08073992, 15.18848345, 21.13149968, 16.23207487,
        14.77677431, 15.01073554,  7.46914481, 12.74684138, 13.56024353],
       [18.38994766, 14.61801106, 14.68873406, 16.23207487, 25.62526578,
        19.05122255, 17.05366754, 13.23738427, 14.5069479 , 10.46190127],
       [17.9994606 , 15.17056066, 13.23912861, 14.77677431, 19.05122255,
        26.3360404 , 16.60032986, 11.98485753, 13.83738431, 11.12337607],
       [17.30343841, 12.89497642, 14.96902782, 15.01073554, 17.05366754,
        16.60032986, 20.86494629,  8.51011924

In [91]:
sector_name = ['INDU', 'HLTH', 'INFT', 'TCOM', 'DSCR', 'FINA', 'MATS', 'REAL', 'STPL', 'ENER']

In [92]:
compare = pd.DataFrame(Pi, index = sector_name, columns = ['Pi'] )

In [93]:
compare['BL'] = nu

In [94]:
compare

Pi        BL
INDU  0.209  0.203060
HLTH  0.411  0.491284
INFT  0.327  0.395539
TCOM  0.097  0.158547
DSCR  0.311  0.335140
FINA -0.160  0.034432
MATS  0.261  0.289704
REAL  0.363  0.340658
STPL  0.132  0.159310
ENER  0.174  0.194926

In [95]:
def statistics(weights):
    weights1 = np.array(weights)
    port_ret = np.dot(weights1.T,nu)
    port_var = np.dot(weights1.T, np.dot(up_cov, weights1))
    return np.array([port_ret,port_var])

In [96]:
def min_negareturn(weights):
    return -statistics(weights)[0]

In [97]:
cons2=({'type': 'ineq', 'fun': lambda x: -statistics(x)[1] + month_var})
opt2 = so.minimize(min_negareturn,10*[1./10,],method='SLSQP', constraints=cons2)

In [98]:
new = np.around(opt2.x,decimals = 4)

In [99]:
compare_weight = pd.DataFrame(old, index = sector_name, columns = ['old'] )
compare_weight['new'] = new

In [100]:
compare_weight

old     new
INDU -0.0775 -0.4068
HLTH  0.6425  0.7809
INFT  0.1167  0.2124
TCOM -0.3168 -0.3425
DSCR  0.2660  0.2876
FINA -0.7314 -0.4679
MATS  0.2678  0.2896
REAL  0.2189  0.1505
STPL -0.0537 -0.1443
ENER  0.0379  0.0443